Bandter/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Bandter.Models
{
    public class Event
    {
        public int EventId { get; set; }
        public string Title { get; set; }
        public int LocationId { get; set; }

        [DisplayFormat(DataFormatString ="{MM/dd/yyyy}")]
        public DateTime EventDate { get; set; }
        public string Description { get; set; }
        public string Zipcode { get; set; }
        public int? Going { get; set; }

    }
}

Bandter/ViewModels/EventViewModel.cs
using Bandter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bandter.ViewModels
{
    public class EventViewModel
    {
        public List<Event> EventsList { get; set; }
        public string CityName { get; set; }
    }
}

Bandter/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Bandter.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bandter.Controllers
{
    public class EventController : Controller
    {
        private BanderDbContext context;

        public EventController(BanderDbContext db)
        {
            context = db;
        }

        public IActionResult CreateEvent()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateEvent(string eventTitle, DateTime eventDate, string eventDescription, string locationStreet, string locationCity, string locationState, string locationZip)
        {
            Location newLocation = new Location()
            {
                Street = locationStreet,
                City = locationCity,
                State = locationState,
                Zipcode = locationZip
            };
            context.Locations.Add(newLocation);
            context.SaveChanges();
            Event newEvent = new Event()
            {
                Title = eventTitle,
                EventDate = eventDate,
                LocationId = newLocation.LocationId,
                Description = eventDescription,
                Zipcode = locationZip,
                Going = 0
            };
            context.Events.Add(newEvent);
            context.SaveChanges();

            return RedirectToAction("UserPage", "Main");
        }

        [HttpPost]
        public IActionResult RSVP(int eventId)
        {
            var rsvpEvent = context.Events.Where(e => e.EventId == eventId).FirstOrDefault();
            rsvpEvent.Going++;
            context.SaveChanges();
            var route = rsvpEvent.Zipcode;

            return RedirectToAction("EventsView", "Main", new { zip = route });
        }
    }
}

Bandter/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Bandter.ViewModels;
using Microsoft.EntityFrameworkCore;
using Bandter.Models;

namespace Bandter.Controllers
{
    public class MainController : Controller
    {
        private BanderDbContext context;

        public MainController(BanderDbContext db)
        {
            context = db;
        }

        public IActionResult UserPage()
        {
            return View();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult EventsView(string zip)
        {
            EventViewModel model = new EventViewModel();
            List<Event> events = new List<Event>();
            model.EventsList = events;
            var city = context.Locations.Where(l => l.Zipcode == zip).FirstOrDefault();
            if(city == null)
            {
                model.CityName = "There are currently no events in this area...";
                return View(model);
            }
            model.CityName = "Events in " + city.City + "...";

            foreach (var e in context.Events)
            {
                if(e.Zipcode == zip)
                {
                    model.EventsList.Add(e);
                }
            }

            return View(model);
        }
    }
}

Bandter/Views/Main/EventsView.cshtml
@model Bandter.ViewModels.EventViewModel
@{
    ViewData["Title"] = "Events";
}


<div class="row pt-1">
    <div class="col offset-2">
        <h3>@Html.DisplayFor(c => c.CityName)</h3>
    </div>
</div>
<hr/>
<div class="row">
    <div class="col-md-8 offset-2">       
        @foreach(var e in Model.EventsList)
        {
            <div class="card" style="padding: 5px; margin:5px;">
                <div class="card-body">
                    <div class="card-header">

                        <div class="d-flex justify-content-between align-items-center">
                            <h5 class="my-auto">@e.EventDate.Date.ToShortDateString()</h5>
                            <p class="float-right my-auto">Going: @e.Going</p>
                        </div>

                        
                    </div>
                    
                    <div class="card-body">
                        <form class="form-inline">
                            <h4>Title: </h4>
                            <h4>@e.Title</h4>
                        </form>
                                    
                        <h6>Description:</h6>
                        <p class="card-text">@e.Description</p>
                        <form method="post" asp-action="RSVP" asp-controller="Event">
                            <input type="hidden" name="eventId" value="@e.LocationId" />
                            <input class="btn btn-success float-right" type="submit" value="RSVP" />
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

Bandter/Views/Main/Index.cshtml
@{
    ViewData["Title"] = "Events";
}

@*TODO: MAKE THIS PAGE A STORE FRONT ABOUT ME PAGE...RECOMMEND SIGN UP!*@

Bandter/Views/Main/UserPage.cshtml
@{
    ViewData["Title"] = "Events";
}
    <hr/>
    <div class="row">
        <div class="col-md-3">
            <div class="card">
                <img src="~/images/block.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">Find musicians in your area!</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <img src="~/images/flyer.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">Tell the world about your event!</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <img src="~/images/dj.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">Let em' know where you're spinning.</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <img src="~/images/drumguy.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                    <p class="card-text">Build a community!</p>
                </div>
            </div>
        </div>
    </div>
    